In [193]:
import math
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from itertools import permutations
from itertools import combinations

In [2]:
olist_1 = pd.read_csv("./olist.csv", index_col=0)
olist_2 = pd.read_csv("./olist_final_df.csv", index_col=0)
olist_pivot = olist_2.pivot_table(
    index="customer_unique_id", columns="product_id", 
    values="review_score"
)
olist_imputed = olist_pivot.fillna(olist_pivot.mean(axis=0))

display(olist_pivot.head())
display(olist_imputed.head())

product_id                        0152f69b6cf919bcdaf117aa8c43e5a2  \
customer_unique_id                                                   
0064a1b5f5cddd047c987b988a90c8c1                               NaN   
0096c18412349537abc45e350581cbbc                               NaN   
00da34ebf22b87f6c2f53dc069f237df                               NaN   
015b72d1a4ec2bfcf75518ada117c62b                               NaN   
01626676a41ff29901f7b42bc8e09dd8                               NaN   

product_id                        017692475c1c954ff597feda05131d73  \
customer_unique_id                                                   
0064a1b5f5cddd047c987b988a90c8c1                               NaN   
0096c18412349537abc45e350581cbbc                               NaN   
00da34ebf22b87f6c2f53dc069f237df                               NaN   
015b72d1a4ec2bfcf75518ada117c62b                               NaN   
01626676a41ff29901f7b42bc8e09dd8                               NaN   

product_id                        0502d1a36be75bd36b452f31c6ed264a  \
customer_unique_id                                                   
0064a1b5f5cddd047c987b988a90c8c1                               NaN   
0096c18412349537abc45e350581cbbc                               NaN   
00da34ebf22b87f6c2f53dc069f237df                               NaN   
015b72d1a4ec2bfcf75518ada117c62b                               NaN   
01626676a41ff29901f7b42bc8e09dd8                               NaN   

product_id                        054515fd15bc1a2029f10de97ffa9120  \
customer_unique_id                                                   
0064a1b5f5cddd047c987b988a90c8c1                               NaN   
0096c18412349537abc45e350581cbbc                               NaN   
00da34ebf22b87f6c2f53dc069f237df                               NaN   
015b72d1a4ec2bfcf75518ada117c62b                               NaN   
01626676a41ff29901f7b42bc8e09dd8                               NaN   

product_id                        060c17562f97e5bb60bc0dfa4dd5b3f2  \
customer_unique_id                                                   
0064a1b5f5cddd047c987b988a90c8c1                               NaN   
0096c18412349537abc45e350581cbbc                               NaN   
00da34ebf22b87f6c2f53dc069f237df                               NaN   
015b72d1a4ec2bfcf75518ada117c62b                               NaN   
01626676a41ff29901f7b42bc8e09dd8                               NaN   

product_id                        060cb19345d90064d1015407193c233d  \
customer_unique_id                                                   
0064a1b5f5cddd047c987b988a90c8c1                               NaN   
0096c18412349537abc45e350581cbbc                               NaN   
00da34ebf22b87f6c2f53dc069f237df                               NaN   
015b72d1a4ec2bfcf75518ada117c62b                               NaN   
01626676a41ff29901f7b42bc8e09dd8                               NaN   

product_id                        06edb72f1e0c64b14c5b79353f7abea3  \
customer_unique_id                                                   
0064a1b5f5cddd047c987b988a90c8c1                               NaN   
0096c18412349537abc45e350581cbbc                               NaN   
00da34ebf22b87f6c2f53dc069f237df                               NaN   
015b72d1a4ec2bfcf75518ada117c62b                               NaN   
01626676a41ff29901f7b42bc8e09dd8                               NaN   

product_id                        08574b074924071f4e201e151b152b4e  \
customer_unique_id                                                   
0064a1b5f5cddd047c987b988a90c8c1                               NaN   
0096c18412349537abc45e350581cbbc                               NaN   
00da34ebf22b87f6c2f53dc069f237df                               NaN   
015b72d1a4ec2bfcf75518ada117c62b                               NaN   
01626676a41ff29901f7b42bc8e09dd8                               NaN   

product_id                        086351823300e0339f6955b27998c186  \
cu

product_id                        0152f69b6cf919bcdaf117aa8c43e5a2  \
customer_unique_id                                                   
0064a1b5f5cddd047c987b988a90c8c1                               3.0   
0096c18412349537abc45e350581cbbc                               3.0   
00da34ebf22b87f6c2f53dc069f237df                               3.0   
015b72d1a4ec2bfcf75518ada117c62b                               3.0   
01626676a41ff29901f7b42bc8e09dd8                               3.0   

product_id                        017692475c1c954ff597feda05131d73  \
customer_unique_id                                                   
0064a1b5f5cddd047c987b988a90c8c1                               5.0   
0096c18412349537abc45e350581cbbc                               5.0   
00da34ebf22b87f6c2f53dc069f237df                               5.0   
015b72d1a4ec2bfcf75518ada117c62b                               5.0   
01626676a41ff29901f7b42bc8e09dd8                               5.0   

product_id                        0502d1a36be75bd36b452f31c6ed264a  \
customer_unique_id                                                   
0064a1b5f5cddd047c987b988a90c8c1                               3.0   
0096c18412349537abc45e350581cbbc                               3.0   
00da34ebf22b87f6c2f53dc069f237df                               3.0   
015b72d1a4ec2bfcf75518ada117c62b                               3.0   
01626676a41ff29901f7b42bc8e09dd8                               3.0   

product_id                        054515fd15bc1a2029f10de97ffa9120  \
customer_unique_id                                                   
0064a1b5f5cddd047c987b988a90c8c1                          3.333333   
0096c18412349537abc45e350581cbbc                          3.333333   
00da34ebf22b87f6c2f53dc069f237df                          3.333333   
015b72d1a4ec2bfcf75518ada117c62b                          3.333333   
01626676a41ff29901f7b42bc8e09dd8                          3.333333   

product_id                        060c17562f97e5bb60bc0dfa4dd5b3f2  \
customer_unique_id                                                   
0064a1b5f5cddd047c987b988a90c8c1                               4.0   
0096c18412349537abc45e350581cbbc                               4.0   
00da34ebf22b87f6c2f53dc069f237df                               4.0   
015b72d1a4ec2bfcf75518ada117c62b                               4.0   
01626676a41ff29901f7b42bc8e09dd8                               4.0   

product_id                        060cb19345d90064d1015407193c233d  \
customer_unique_id                                                   
0064a1b5f5cddd047c987b988a90c8c1                               5.0   
0096c18412349537abc45e350581cbbc                               5.0   
00da34ebf22b87f6c2f53dc069f237df                               5.0   
015b72d1a4ec2bfcf75518ada117c62b                               5.0   
01626676a41ff29901f7b42bc8e09dd8                               5.0   

product_id                        06edb72f1e0c64b14c5b79353f7abea3  \
customer_unique_id                                                   
0064a1b5f5cddd047c987b988a90c8c1                          3.285714   
0096c18412349537abc45e350581cbbc                          3.285714   
00da34ebf22b87f6c2f53dc069f237df                          3.285714   
015b72d1a4ec2bfcf75518ada117c62b                          3.285714   
01626676a41ff29901f7b42bc8e09dd8                          3.285714   

product_id                        08574b074924071f4e201e151b152b4e  \
customer_unique_id                                                   
0064a1b5f5cddd047c987b988a90c8c1                               3.2   
0096c18412349537abc45e350581cbbc                               3.2   
00da34ebf22b87f6c2f53dc069f237df                               3.2   
015b72d1a4ec2bfcf75518ada117c62b                               3.2   
01626676a41ff29901f7b42bc8e09dd8                               3.2   

product_id                        086351823300e0339f6955b27998c186  \
cu

In [3]:
print(olist_pivot.loc['00da34ebf22b87f6c2f53dc069f237df'][olist_pivot.loc['00da34ebf22b87f6c2f53dc069f237df'].notnull()])
print(olist_pivot.loc['0064a1b5f5cddd047c987b988a90c8c1'][olist_pivot.loc['0064a1b5f5cddd047c987b988a90c8c1'].notnull()])

product_id
aca2eb7d00ea1a7b8ebd4e68314663af    3.0
Name: 00da34ebf22b87f6c2f53dc069f237df, dtype: float64
product_id
368c6c730842d78016ad823897a372db    5.0
Name: 0064a1b5f5cddd047c987b988a90c8c1, dtype: float64


In [4]:
print(olist_imputed.loc['00da34ebf22b87f6c2f53dc069f237df'][olist_imputed.loc['00da34ebf22b87f6c2f53dc069f237df'].notnull()])
print(olist_imputed.loc['0064a1b5f5cddd047c987b988a90c8c1'][olist_imputed.loc['0064a1b5f5cddd047c987b988a90c8c1'].notnull()])

product_id
0152f69b6cf919bcdaf117aa8c43e5a2    3.000000
017692475c1c954ff597feda05131d73    5.000000
0502d1a36be75bd36b452f31c6ed264a    3.000000
054515fd15bc1a2029f10de97ffa9120    3.333333
060c17562f97e5bb60bc0dfa4dd5b3f2    4.000000
                                      ...   
fb55982be901439613a95940feefd9ee    2.000000
fb7a100ec8c7b34f60cec22b1a9a10e0    3.000000
fbc1488c1a1e72ba175f53ab29a248e8    5.000000
fe077ec80df6b4ee60bb4498d5ab1962    5.000000
fe6a9515d655fa7936b8a7c841039f34    5.000000
Name: 00da34ebf22b87f6c2f53dc069f237df, Length: 323, dtype: float64
product_id
0152f69b6cf919bcdaf117aa8c43e5a2    3.000000
017692475c1c954ff597feda05131d73    5.000000
0502d1a36be75bd36b452f31c6ed264a    3.000000
054515fd15bc1a2029f10de97ffa9120    3.333333
060c17562f97e5bb60bc0dfa4dd5b3f2    4.000000
                                      ...   
fb55982be901439613a95940feefd9ee    2.000000
fb7a100ec8c7b34f60cec22b1a9a10e0    3.000000
fbc1488c1a1e72ba175f53ab29a248e8    5.000000
fe077ec80d

In [309]:
def triangle_prime(user_item_matrix, items=False):
    user_item = user_item_matrix.T if items else user_item_matrix
    nr_users = user_item.shape[0]

    sum_1 = np.array([
        np.sqrt(np.sum(np.square(np.diff(comb, axis=0)))) 
        for comb in combinations(user_item, 2)])
    user_sums = np.sqrt(np.sum(np.square(user_item), axis=1))
    sum_2 = np.array([np.sum(i) for i in combinations(user_sums, 2)])

    sum_3 = 1 - (sum_1 / sum_2)

    tri = np.zeros((nr_users, nr_users))
    tri[np.triu_indices(nr_users, 1)] = sum_3

    return tri

def urp(user_item_matrix, items=False):
    user_item_masked = np.ma.array(
        user_item_matrix.T if items else user_item_matrix)

    nr_users = user_item_masked.shape[0]
    user_item_masked = np.ma.masked_where(
        user_item_masked == 0, 
        user_item_masked)

    means = user_item_masked.mean(axis=1).data
    stds = user_item_masked.std(axis=1).data

    mean_diffs = np.array([
        np.abs(np.diff(mean)) for mean in combinations(means, 2)])
    std_diffs = np.array([
        np.abs(np.diff(std)) for std in combinations(stds, 2)])

    tri_upper = (1 - 1/(1+np.exp(-1 * mean_diffs * std_diffs))).squeeze()

    tri = np.zeros((nr_users, nr_users))
    tri[np.triu_indices(nr_users, 1)] = tri_upper

    return tri

def itr(user_item_matrix, items=False, full_matrix=False):
    triangle_res = triangle_prime(user_item_matrix, items=items)
    # print("Triangle'")
    # print(triangle_res)

    urp_res = urp(user_item_matrix, items=items) 
    # print("URP")
    # print(urp_res)

    itr_res = triangle_res * urp_res

    if full_matrix:
        itr_res += itr_res.T

    return itr_res
    

In [311]:
np.set_printoptions(precision=3)

user_item = np.array([
    [4, 3, 5, 4, 2],
    [5, 1, 0, 0, 4],
    [4, 2, 1, 2, 1],
    [2, 1, 0, 1, 2],
    [4, 2, 2, 0, 2],
])

urp_paper = np.array([
    [0, 0.386, 0.306, 0.403, 0.5],
    [0, 0, 0.304, 0.433, 0.476],
    [0, 0, 0, 0.462, 0.416],
    [0, 0, 0, 0, 0.491],
    [0, 0, 0, 0, 0],
])

result_itr = itr(user_item, items=True, full_matrix=False)
# result_urp = urp(user_item, items=True)
# result_triangle = np.zeros_like(user_item, dtype=np.float32)

# for i in range(user_item.shape[0]):
#     for j in range(user_item.shape[1]):
#         # result_itr[i, j] = itr(user_item[i], user_item[j])
#         result_triangle[i, j] = triangle_prime(user_item[i], user_item[j])

print("ITR")
print(result_itr)

# print("ITR")
# print(np.triu(result_triangle, k=1) * result_urp)

ITR
[[0.    0.236 0.166 0.198 0.35 ]
 [0.    0.    0.223 0.315 0.307]
 [0.    0.    0.    0.341 0.21 ]
 [0.    0.    0.    0.    0.24 ]
 [0.    0.    0.    0.    0.   ]]


In [288]:


user_item = np.array([
    [4, 3, 5, 4, 2],
    [5, 1, 0, 0, 4],
    [4, 2, 1, 2, 1],
    [2, 1, 0, 1, 2],
    [4, 2, 2, 0, 2],
])

print(triangle_prime(user_item, items=True))

[[0.    0.612 0.54  0.492 0.7  ]
 [0.    0.    0.731 0.726 0.644]
 [0.    0.    0.    0.737 0.504]
 [0.    0.    0.    0.    0.488]
 [0.    0.    0.    0.    0.   ]]
